# files to ignore checking

AllCops:
  TargetRubyVersion: 3.1.3
  Exclude:
    - "./bin/**/*"
    - './db/migrate/*'

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Max: 50

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 50

Layout/LineLength:
  Max: 250

Metrics/ClassLength:
  Max: 300