version: '3.4'

services:
  ite_portal_api: 
    build:
      context: .
      dockerfile: local_docker/Dockerfile
    depends_on:
      - database
    ports: 
      - "4000:4000"
    volumes:
      - .:/dbh
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/dbh/node_modules
    restart: unless-stopped
    environment:
      RAILS_ENV: development
    command: bash -c "bundle exec rails db:prepare && bundle exec rails s -b 0.0.0.0 -p 4000"

  database:
    image: mcr.microsoft.com/azure-sql-edge
    ports:
      - "14301:14301"
    volumes:
      - db_data:/var/opt/mssql
    environment:
      - MSSQL_SA_PASSWORD=${SA_PASSWORD}
      - ACCEPT_EULA=1
      - MSSQL_USER=SA

volumes:
  gem_cache:
  db_data:
  node_modules: 