name: Publish PRE-Release (to UAT)

on:
  release:
    types:
      - prereleased

concurrency:
  group: uat-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-to-awsecs:
    runs-on: ubuntu-latest
    environment: uat
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy Image on Fargate
        run: |
          aws ecs update-service --cluster "dbh-ite" --service "dbhiteportal-uat-bff" --force-new-deployment
      - name: Wait For Deployment To Complete
        run: |
          sleep 15
          aws ecs wait services-stable --cluster "dbh-ite" --services "dbhiteportal-uat-bff"
