name: Publish Release (to PROD)

on:
  release:
    types:
      - released

concurrency:
  group: prod-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-to-awsecs:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v3
      - name: Install FreeTDS
        run: |
          sudo apt install -y freetds-dev
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      # - name: Update DB
      #   env:
      #     ITE_PORTAL_API_DATABASE_HOST: ${{ secrets.PROVIDER_GATEWAY_API_DATABASE_HOST }}
      #     ITE_PORTAL_API_DATABASE_USERNAME: ${{ secrets.PROVIDER_GATEWAY_API_DATABASE_USERNAME }}
      #     ITE_PORTAL_API_DATABASE_PASSWORD: ${{ secrets.PROVIDER_GATEWAY_API_DATABASE_PASSWORD }}
      #     ITE_PORTAL_API_DATABASE_DATABASE: 'ite_portal_api_production'
      #     RAILS_ENV: production
      #   run: |
      #     bin/rails db:create
      #     bin/rails db:migrate
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy Image on Fargate
        run: |
          aws ecs update-service --cluster "dbh-ite" --service "dbhiteportal-prod-bff" --force-new-deployment
      - name: Wait For Deployment To Complete
        run: |
          sleep 15
          aws ecs wait services-stable --cluster "dbh-ite" --services "dbhiteportal-prod-bff"