name: Test, Build, Deploy (to DEV)

concurrency:
  group: dev-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - trunk

jobs:
  test:
    runs-on: ubuntu-latest
    services:
#      mongo:
#       image: mongo:5.0
#        ports:
#          - 27017:27017
#        options: >-
#          --name "mongo"
#          --health-cmd mongo
#          --health-interval 10s
#          --health-timeout 5s
#          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bundle exec rspec

  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
      - uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-multi-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-multi-buildx
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - uses: docker/login-action@v2
        with:
          registry: "public.ecr.aws"
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Build Image
        uses: docker/build-push-action@v3
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          file: Dockerfile
          # Set the desired build target here
          push: ${{ github.event_name != 'pull_request' }}
          tags: public.ecr.aws/ideacrew/ite-portal-api:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          # Note the mode=max here
          # More: https://github.com/moby/buildkit#--export-cache-options
          # And: https://github.com/docker/buildx#--cache-tonametypetypekeyvalue
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

#   deploy-to-heroku:
#     needs: [test]
#     runs-on: ubuntu-latest
#     environment: dev
#     steps:
#       - uses: actions/checkout@v3
#       - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
#         with:
#           heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
#           heroku_app_name: "ite-api" #Must be unique in Heroku
#           heroku_email: "kristin.merbach@ideacrew.com"
#           usedocker: true
#         env:
#           HD_MONGODB_URI: ${{ secrets.MONGODB_URI }}

  deploy-to-awsecs:
    needs: [test]
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy Image on Fargate
        run: |
          aws ecs update-service --cluster "dbh-ite" --service "dbhiteportal-dev-bff" --force-new-deployment
      - name: Wait For Deployment To Complete
        run: |
          sleep 15
          aws ecs wait services-stable --cluster "dbh-ite" --services "dbhiteportal-dev-bff"
